// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dlpamlngvsugbqopciqq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRscGFtbG5ndnN1Z2Jxb3BjaXFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg1NjA5NjYsImV4cCI6MjA1NDEzNjk2Nn0.sLSByyLyAi0zpPWsmAa74tZ_tr0LlZjKMry4vCLSAcA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);